using System.Security.Cryptography; using System.Text; using BackendAPI.Interfaces; using BackendAPI.Models; using BackendAPI.Services;
namespace BackendAPI.Repository;
public sealed class LiveRoomsRepository(IPollPacksRepository packs,IConfiguration config) : ILiveRoomsRepository
{
 readonly object gate=new(); readonly Dictionary<Guid,LiveRoomState> rooms=[];
 public Task<HostRoomSnapshot> CreateAsync(long host,CreateLiveRoomRequest q,DateTime now){lock(gate){var pack=packs.GetUsable(q.PackId,host);var max=config.GetValue("LiveRooms:MaximumParticipants",100);if(q.ParticipantLimit<1||q.ParticipantLimit>max)throw new LiveRoomException("invalid_limit",$"Limit must be between 1 and {max}.");var r=new LiveRoomState{HostId=host,Code=Code(),DisplayToken=Token(),Mode=q.Mode,Rules=q.Rules??new(),Limit=q.ParticipantLimit,Status=LiveRoomStatus.Lobby,ExpiresAt=now.AddHours(config.GetValue("LiveRooms:LifetimeHours",6)),Propositions=pack.Items.OrderBy(x=>x.Position).Select(x=>x.Proposition).ToList()};rooms.Add(r.Id,r);return Task.FromResult(LiveRoomProjector.Host(r));}}
 public Task<HostRoomSnapshot> HostAsync(Guid id,long host,DateTime now){lock(gate){var r=Room(id,now);Own(r,host);return Task.FromResult(LiveRoomProjector.Host(r));}}
 public Task<DisplayRoomSnapshot> DisplayAsync(Guid id,string token,DateTime now){lock(gate){var r=Room(id,now);if(!Fixed(r.DisplayToken,token))throw new UnauthorizedAccessException();return Task.FromResult(LiveRoomProjector.Display(r));}}
 public Task<JoinLiveRoomResponse> JoinAsync(JoinLiveRoomRequest q,DateTime now){lock(gate){var r=rooms.Values.FirstOrDefault(x=>x.Code.Equals(q.Code.Trim(),StringComparison.OrdinalIgnoreCase))??throw new LiveRoomException("not_found","Room not found.");Room(r.Id,now);if(!string.IsNullOrWhiteSpace(q.ReconnectToken)){var old=r.Participants.FirstOrDefault(x=>Fixed(x.TokenHash,Hash(q.ReconnectToken)));if(old is null||old.Removed)throw new UnauthorizedAccessException();return Task.FromResult(new JoinLiveRoomResponse(r.Id,old.Id,q.ReconnectToken,LiveRoomProjector.Participant(r,old)));}LiveRoomRules.EnsureCanJoin(r.Participants.Count(x=>!x.Removed),r.Limit,r.Status,r.ExpiresAt,now);if(string.IsNullOrWhiteSpace(q.DisplayName)||q.DisplayName.Trim().Length>40)throw new LiveRoomException("invalid_name","Enter a display name up to 40 characters.");var token=Token();var p=new LiveParticipantState{Name=q.DisplayName.Trim(),TokenHash=Hash(token),EligibleFrom=r.Round?.Status==LiveRoundStatus.Open?r.Position+1:Math.Max(0,r.Position)};r.Participants.Add(p);r.Version++;return Task.FromResult(new JoinLiveRoomResponse(r.Id,p.Id,token,LiveRoomProjector.Participant(r,p)));}}
 public Task<ParticipantRoomSnapshot> ParticipantAsync(Guid id,string token,DateTime now){lock(gate){var r=Room(id,now);return Task.FromResult(LiveRoomProjector.Participant(r,Person(r,token)));}}
 public Task<ParticipantRoomSnapshot> VoteAsync(Guid id,string token,LiveVoteRequest q,DateTime now){lock(gate){var r=Room(id,now);var p=Person(r,token);var round=r.Round;if(r.Status!=LiveRoomStatus.Active||round?.Status!=LiveRoundStatus.Open)throw new LiveRoomException("round_closed","Voting is not open.");if(!LiveRoomRules.IsEligible(p.EligibleFrom,r.Position))throw new LiveRoomException("late_join","You become eligible next round.");if(round.Votes.ContainsKey(p.Id))throw new LiveRoomException("already_voted","Vote already submitted.");if(r.Mode==LiveRoomMode.PredictMajority&&q.PredictedMajority is null)throw new LiveRoomException("prediction_required","Predict the majority.");round.Votes.Add(p.Id,(q.Choice,q.PredictedMajority));r.Version++;return Task.FromResult(LiveRoomProjector.Participant(r,p));}}
 public Task<HostRoomSnapshot> CommandAsync(Guid id,long host,string command,Guid? participant,DateTime now){lock(gate){var r=Room(id,now);Own(r,host);if(command=="remove"){var p=r.Participants.FirstOrDefault(x=>x.Id==participant&&!x.Removed)??throw new LiveRoomException("not_found","Participant not found.");p.Removed=true;r.Version++;return Task.FromResult(LiveRoomProjector.Host(r));}LiveRoomRules.EnsureTransition(r.Status,command);if(command=="advance"&&r.Round?.Status!=LiveRoundStatus.Revealed)throw new LiveRoomException("invalid_transition","Reveal the current round before advancing.");if(command=="close"&&r.Round?.Status!=LiveRoundStatus.Open)throw new LiveRoomException("invalid_transition","Only an open round can be revealed.");switch(command){case "start":r.Status=LiveRoomStatus.Active;OpenNext(r);break;case "pause":r.Status=LiveRoomStatus.Paused;if(r.Round is not null)r.Round.Status=LiveRoundStatus.Paused;break;case "resume":r.Status=LiveRoomStatus.Active;if(r.Round is not null)r.Round.Status=LiveRoundStatus.Open;break;case "close":Reveal(r);break;case "advance":if(r.Position+1>=r.Propositions.Count){r.Status=LiveRoomStatus.Ended;}else{r.Status=LiveRoomStatus.Active;OpenNext(r);}break;case "end":r.Status=LiveRoomStatus.Ended;break;}r.Version++;return Task.FromResult(LiveRoomProjector.Host(r));}}
 public Task ExpireAsync(DateTime now){lock(gate){foreach(var r in rooms.Values.Where(x=>x.Status is not(LiveRoomStatus.Ended or LiveRoomStatus.Expired)&&x.ExpiresAt<=now)){r.Status=LiveRoomStatus.Expired;r.Version++;}}return Task.CompletedTask;}
 void OpenNext(LiveRoomState r){r.Position++;r.Round=new(){Position=r.Position,Proposition=r.Propositions[r.Position]};}
 static void Reveal(LiveRoomState r){if(r.Round is null)return;foreach(var x in LiveRoomScoring.Score(r.Mode,r.Rules,r.Round.Votes))r.Participants.First(p=>p.Id==x.Key).Score+=x.Value;r.Round.Status=LiveRoundStatus.Revealed;}
 LiveRoomState Room(Guid id,DateTime now){var r=rooms.GetValueOrDefault(id)??throw new LiveRoomException("not_found","Room not found.");if(r.ExpiresAt<=now&&r.Status is not(LiveRoomStatus.Ended or LiveRoomStatus.Expired)){r.Status=LiveRoomStatus.Expired;r.Version++;}return r;}
 static void Own(LiveRoomState r,long host){if(r.HostId!=host)throw new UnauthorizedAccessException();} static LiveParticipantState Person(LiveRoomState r,string token)=>r.Participants.FirstOrDefault(x=>!x.Removed&&Fixed(x.TokenHash,Hash(token)))??throw new UnauthorizedAccessException();
 static string Token()=>Convert.ToHexString(RandomNumberGenerator.GetBytes(24));static string Code()=>new string(RandomNumberGenerator.GetBytes(6).Select(x=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[x%32]).ToArray());static string Hash(string x)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(x)));static bool Fixed(string a,string b)=>CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(a),Encoding.UTF8.GetBytes(b));
}
