namespace BackendAPI.Models
{
    public class Poll
    {
        public long Id { get; set; }
        public string Question { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string Category { get; set; } = string.Empty;
        public bool IsTrending { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime ExpiresAt { get; set; }
        public DateTime CreatedAt { get; set; }
        public int TotalVotes { get; set; }
        public long? CreatedByUserId { get; set; }
        public string? CreatedByUsername { get; set; }
        public string? CreatedByDisplayName { get; set; }
        public bool IsSponsored { get; set; }
        public long? BusinessId { get; set; }
        public long? CampaignId { get; set; }
        public string? SponsorName { get; set; }
        public string? CampaignName { get; set; }
        public bool IsPrivate { get; set; }
        public bool IsWellness { get; set; }
        public string PollMode { get; set; } = PollModes.Public;
        public string ModerationStatus { get; set; } = PollModerationStatus.Published;
        public string? ModerationReason { get; set; }
        public long? ModeratedByUserId { get; set; }
        public DateTime? ModeratedAt { get; set; }
        public int ReportCount { get; set; }
        public DateTime? LastReportedAt { get; set; }

        // ── Ingestion / AI fields (US-01) ────────────────────────────────────
        /// <summary>Origin of the poll: "rss" | "youtube" | "gnews" | "manual"</summary>
        public string? SourceType { get; set; }
        /// <summary>Original article / video URL used to generate this poll.</summary>
        public string? SourceUrl { get; set; }
        /// <summary>Thumbnail image URL for the poll card.</summary>
        public string? ThumbnailUrl { get; set; }
        /// <summary>True when the question + options were generated by the AI model.</summary>
        public bool IsAIGenerated { get; set; }
        public string GenerationMethod { get; set; } = GenerationMethods.ManualReview;
        public string? GenerationProvider { get; set; }
        public string? GenerationModel { get; set; }

        public List<PollOption> Options { get; set; } = new();

        // ── US-16: Per-user vote state (populated when request is authenticated) ──
        /// <summary>True when the authenticated user has already voted on this poll.</summary>
        public bool HasVoted { get; set; }
        /// <summary>The OptionId the user chose, or null if not voted / unauthenticated.</summary>
        public long? UserVotedOptionId { get; set; }
    }

    public class PollOption
    {
        public long Id { get; set; }
        public long PollId { get; set; }
        public string Text { get; set; } = string.Empty;
        /// <summary>Stable binary identity. Required for generated polls; null for custom/legacy polls.</summary>
        public string? Side { get; set; }
        public int VoteCount { get; set; }
        public double VotePercentage { get; set; }
    }

    public class CreatePollRequest
    {
        public string Question { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string Category { get; set; } = string.Empty;
        public DateTime ExpiresAt { get; set; }
        public List<string> Options { get; set; } = new();

        // Optional ingestion metadata
        public string? SourceType { get; set; }
        public string? SourceUrl { get; set; }
        public string? ThumbnailUrl { get; set; }
        public bool IsAIGenerated { get; set; }
        public string GenerationMethod { get; set; } = GenerationMethods.ManualReview;
        public long? TrendingTopicId { get; set; }
        public string? GenerationProvider { get; set; }
        public string? GenerationModel { get; set; }
        [System.Text.Json.Serialization.JsonIgnore]
        public GeneratedPollQualityDecision? QualityDecision { get; set; }
        [System.Text.Json.Serialization.JsonIgnore]
        public bool AutoPublish { get; set; }
        public bool IsPrivate { get; set; }
        public bool IsWellness { get; set; }
        public string? ModerationReason { get; set; }
    }

    public static class PollModes
    {
        public const string Public = "Public";
        public const string Wellness = "Wellness";
    }

    public static class GenerationMethods
    {
        public const string Llm = "Llm";
        public const string DeterministicFallback = "DeterministicFallback";
        public const string ManualReview = "ManualReview";
    }

    public static class TopicConversionStatuses
    {
        public const string Pending = "Pending";
        public const string RetryPending = "RetryPending";
        public const string Converted = "Converted";
        public const string NeedsReview = "NeedsReview";
        public const string Unconvertible = "Unconvertible";
    }

    // ── TrendingTopics staging table model (US-01) ───────────────────────────
    public static class PollModerationStatus
    {
        public const string Draft = "Draft";
        public const string PendingReview = "PendingReview";
        public const string Published = "Published";
        public const string Rejected = "Rejected";
        public const string Flagged = "Flagged";

        public static readonly HashSet<string> All = new(StringComparer.OrdinalIgnoreCase)
        {
            Draft,
            PendingReview,
            Published,
            Rejected,
            Flagged
        };

        public static string Normalize(string? status, string fallback = Published)
        {
            if (string.IsNullOrWhiteSpace(status)) return fallback;

            return All.TryGetValue(status.Trim(), out var normalized)
                ? normalized
                : fallback;
        }
    }

    public class ReportPollRequest
    {
        public string Reason { get; set; } = string.Empty;
    }

    public class ModeratePollRequest
    {
        public string Status { get; set; } = PollModerationStatus.Published;
        public string? Reason { get; set; }
    }

    public class TrendingTopic
    {
        public long Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Summary { get; set; } = string.Empty;
        public string SourceType { get; set; } = string.Empty;
        public string SourceUrl { get; set; } = string.Empty;
        public string? ThumbnailUrl { get; set; }
        public string? Publisher { get; set; }
        public DateTime? PublishedAt { get; set; }
        public string Category { get; set; } = "General";
        public DateTime FetchedAt { get; set; }
        public bool IsProcessed { get; set; }
        public DateTime? ProcessedAt { get; set; }
        public string ConversionStatus { get; set; } = TopicConversionStatuses.Pending;
        public int AttemptCount { get; set; }
        public DateTime? NextAttemptAt { get; set; }
        public DateTime? LastAttemptAt { get; set; }
        public string? LastFailureKind { get; set; }
        public string? LastFailureReason { get; set; }
        public string? LastGenerationMethod { get; set; }
        public long? GeneratedPollId { get; set; }
    }
}
