namespace BackendAPI.Models
{
    public class Poll
    {
        public long Id { get; set; }
        public string Question { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string Category { get; set; } = string.Empty;
        public bool IsTrending { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime ExpiresAt { get; set; }
        public DateTime CreatedAt { get; set; }
        public int TotalVotes { get; set; }
        public long? CreatedByUserId { get; set; }
        public string? CreatedByUsername { get; set; }
        public string? CreatedByDisplayName { get; set; }

        // ── Ingestion / AI fields (US-01) ────────────────────────────────────
        /// <summary>Origin of the poll: "rss" | "youtube" | "gnews" | "manual"</summary>
        public string? SourceType { get; set; }
        /// <summary>Original article / video URL used to generate this poll.</summary>
        public string? SourceUrl { get; set; }
        /// <summary>Thumbnail image URL for the poll card.</summary>
        public string? ThumbnailUrl { get; set; }
        /// <summary>True when the question + options were generated by the AI model.</summary>
        public bool IsAIGenerated { get; set; }

        public List<PollOption> Options { get; set; } = new();

        // ── US-16: Per-user vote state (populated when request is authenticated) ──
        /// <summary>True when the authenticated user has already voted on this poll.</summary>
        public bool HasVoted { get; set; }
        /// <summary>The OptionId the user chose, or null if not voted / unauthenticated.</summary>
        public long? UserVotedOptionId { get; set; }
    }

    public class PollOption
    {
        public long Id { get; set; }
        public long PollId { get; set; }
        public string Text { get; set; } = string.Empty;
        public int VoteCount { get; set; }
        public double VotePercentage { get; set; }
    }

    public class CreatePollRequest
    {
        public string Question { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string Category { get; set; } = string.Empty;
        public DateTime ExpiresAt { get; set; }
        public List<string> Options { get; set; } = new();

        // Optional ingestion metadata
        public string? SourceType { get; set; }
        public string? SourceUrl { get; set; }
        public string? ThumbnailUrl { get; set; }
        public bool IsAIGenerated { get; set; }
    }

    // ── TrendingTopics staging table model (US-01) ───────────────────────────
    public class TrendingTopic
    {
        public long Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Summary { get; set; } = string.Empty;
        public string SourceType { get; set; } = string.Empty;
        public string SourceUrl { get; set; } = string.Empty;
        public string? ThumbnailUrl { get; set; }
        public string Category { get; set; } = "General";
        public DateTime FetchedAt { get; set; }
        public bool IsProcessed { get; set; }
        public DateTime? ProcessedAt { get; set; }
    }
}
