CREATE TABLE PollPacks (
 Id BIGINT IDENTITY PRIMARY KEY, OwnerUserId BIGINT NOT NULL, Name NVARCHAR(120) NOT NULL,
 Description NVARCHAR(500) NOT NULL DEFAULT '', Visibility VARCHAR(10) NOT NULL DEFAULT 'Private',
 ModerationStatus VARCHAR(20) NOT NULL DEFAULT 'Draft', CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), ModeratedByUserId BIGINT NULL, ModeratedAt DATETIME2 NULL,
 CONSTRAINT CK_PollPacks_State CHECK (ModerationStatus IN ('Draft','PendingReview','Published','Rejected'))
);
CREATE TABLE PollPackItems (
 Id BIGINT IDENTITY PRIMARY KEY, PackId BIGINT NOT NULL REFERENCES PollPacks(Id), Position INT NOT NULL,
 Proposition NVARCHAR(500) NOT NULL, CONSTRAINT UQ_PollPackItems_Position UNIQUE(PackId,Position),
 CONSTRAINT CK_PollPackItems_Proposition CHECK (LEN(LTRIM(RTRIM(Proposition))) > 0)
);
CREATE TABLE LiveRooms (
 Id UNIQUEIDENTIFIER PRIMARY KEY, HostUserId BIGINT NOT NULL, JoinCode VARCHAR(10) NOT NULL UNIQUE,
 DisplayTokenHash CHAR(64) NOT NULL, Mode VARCHAR(30) NOT NULL, RuleConfig NVARCHAR(MAX) NOT NULL,
 Status VARCHAR(12) NOT NULL, CurrentRoundPosition INT NOT NULL DEFAULT -1, ParticipantLimit INT NOT NULL,
 CreatedAt DATETIME2 NOT NULL, LastActivityAt DATETIME2 NOT NULL, ExpiresAt DATETIME2 NOT NULL,
 EndedAt DATETIME2 NULL, Version ROWVERSION, CONSTRAINT CK_LiveRooms_Limit CHECK (ParticipantLimit BETWEEN 1 AND 100)
);
CREATE INDEX IX_LiveRooms_Expiry ON LiveRooms(Status,ExpiresAt);
CREATE TABLE LiveRoomRounds (
 Id BIGINT IDENTITY PRIMARY KEY, RoomId UNIQUEIDENTIFIER NOT NULL REFERENCES LiveRooms(Id), Position INT NOT NULL,
 Proposition NVARCHAR(500) NOT NULL, Status VARCHAR(12) NOT NULL, OpenedAt DATETIME2 NULL, ClosedAt DATETIME2 NULL,
 UpCount INT NOT NULL DEFAULT 0, AgainstCount INT NOT NULL DEFAULT 0, CONSTRAINT UQ_LiveRoomRounds_Position UNIQUE(RoomId,Position)
);
CREATE TABLE LiveRoomParticipants (
 Id UNIQUEIDENTIFIER PRIMARY KEY, RoomId UNIQUEIDENTIFIER NOT NULL REFERENCES LiveRooms(Id), DisplayName NVARCHAR(40) NOT NULL,
 ReconnectTokenHash CHAR(64) NOT NULL, EligibleFromRound INT NOT NULL, Score INT NOT NULL DEFAULT 0,
 JoinedAt DATETIME2 NOT NULL, LastSeenAt DATETIME2 NOT NULL, RemovedAt DATETIME2 NULL
);
CREATE INDEX IX_LiveRoomParticipants_Active ON LiveRoomParticipants(RoomId,RemovedAt);
CREATE TABLE LiveRoomVotes (
 RoundId BIGINT NOT NULL REFERENCES LiveRoomRounds(Id), ParticipantId UNIQUEIDENTIFIER NOT NULL REFERENCES LiveRoomParticipants(Id),
 Choice VARCHAR(8) NOT NULL, Prediction VARCHAR(8) NULL, SubmittedAt DATETIME2 NOT NULL,
 CONSTRAINT PK_LiveRoomVotes PRIMARY KEY(RoundId,ParticipantId), CONSTRAINT CK_LiveRoomVotes_Choice CHECK (Choice IN ('Up','Against')),
 CONSTRAINT CK_LiveRoomVotes_Prediction CHECK (Prediction IS NULL OR Prediction IN ('Up','Against'))
);
