import type { ApiPoll } from "./api"
import { normalizeCategoryName } from "./categories"
import type { PollSide } from "./poll-sides"

// ── Source types ─────────────────────────────────────────────────────────────
// Legacy UI sources (used by existing mock cards)
export type MediaSource = "youtube" | "instagram" | "twitter" | "news" | "tiktok"

// Backend ingestion sources (US-01 / US-10)
export type IngestionSource = "rss" | "youtube" | "gnews" | "manual" | "business"

// ── Poll option (from backend) ────────────────────────────────────────────────
export interface PollOption {
  id: number
  text: string
  side?: PollSide | null
  voteCount: number
  votePercentage: number
}

// ── Poll interface ────────────────────────────────────────────────────────────
export interface Poll {
  id: string
  question: string
  category: string
  trending: boolean
  mediaType: "image" | "video" | "embed"
  mediaUrl: string           // fallback image when no thumbnailUrl
  mediaThumbnail?: string
  source: MediaSource
  sourceLabel: string
  sourceUrl?: string
  totalVotes: number
  yesPercentage: number
  xpReward: number
  timePosted: string

  // ── US-10: Backend ingestion fields (optional — absent on manual/mock polls) ─
  /** "rss" | "youtube" | "gnews" | "manual" — set by the ingestion pipeline */
  sourceType?: IngestionSource
  /** Thumbnail from the original article/video — preferred over mediaUrl */
  thumbnailUrl?: string | null
  /** True when the question + options were generated by the AI model */
  isAIGenerated?: boolean
  isSponsored?: boolean
  sponsorName?: string | null
  campaignName?: string | null
  isPrivate?: boolean
  isWellness?: boolean

  // ── US-12: Full options list for voting (absent on mock polls) ─────────────
  options?: PollOption[]

  // ── US-19: Per-user vote state (from backend when authenticated) ────────────
  /** True when the authenticated user has already voted on this poll. */
  hasVoted?: boolean
  /** The id of the option the user voted for, or null. */
  userVotedOptionId?: number | null
}

// ── Backend → Frontend mapper (US-12) ────────────────────────────────────────

function relativeTime(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime()
  const mins = Math.floor(diff / 60_000)
  if (mins < 60) return `${mins}m ago`
  const hrs = Math.floor(mins / 60)
  if (hrs < 24) return `${hrs}h ago`
  return `${Math.floor(hrs / 24)}d ago`
}

function sourceToMediaSource(sourceType: string | null): MediaSource {
  if (sourceType === "youtube") return "youtube"
  return "news"
}

const PLACEHOLDER_IMAGE =
  "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80"

export function mapBackendPoll(p: ApiPoll): Poll {
  const firstOptionPct = p.options[0]?.votePercentage ?? 0
  const sourceType = (p.sourceType ?? "manual") as IngestionSource

  return {
    id:           String(p.id),
    question:     p.question,
    category:     normalizeCategoryName(p.category),
    trending:     p.isTrending,
    mediaType:    "image",
    mediaUrl:     p.thumbnailUrl ?? PLACEHOLDER_IMAGE,
    source:       sourceToMediaSource(p.sourceType),
    sourceLabel:  p.sourceType ? (SOURCE_LABELS[sourceType] ?? "News") : "Pollify",
    sourceUrl:    p.sourceUrl ?? undefined,
    totalVotes:   p.totalVotes,
    yesPercentage: Math.round(firstOptionPct),
    xpReward:     p.isTrending ? 35 : 25,
    timePosted:   relativeTime(p.createdAt),
    sourceType,
    thumbnailUrl: p.thumbnailUrl,
    isAIGenerated: p.isAIGenerated,
    isSponsored:   p.isSponsored,
    sponsorName:   p.sponsorName,
    campaignName:  p.campaignName,
    isPrivate:     p.isPrivate,
    isWellness:    p.isWellness,
    options:      p.options.map((o) => ({
      id:             o.id,
      text:           o.text,
      side:           o.side,
      voteCount:      o.voteCount,
      votePercentage: o.votePercentage,
    })),
    hasVoted:          p.hasVoted ?? false,
    userVotedOptionId: p.userVotedOptionId ?? null,
  }
}

// ── Mock data ─────────────────────────────────────────────────────────────────
export const MOCK_POLLS: Poll[] = [
  {
    id: "1",
    question: "Should AI-generated art be allowed in art competitions?",
    category: "Technology",
    trending: true,
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
    source: "twitter",
    sourceLabel: "@TechCrunch",
    totalVotes: 24567,
    yesPercentage: 42,
    xpReward: 25,
    timePosted: "2h ago",
    sourceType: "gnews",
    isAIGenerated: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
  },
  {
    id: "2",
    question: "Is remote work better than office work for productivity?",
    category: "Work",
    trending: true,
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1587560699334-cc4ff634909a?w=800&q=80",
    source: "news",
    sourceLabel: "Forbes",
    totalVotes: 89234,
    yesPercentage: 67,
    xpReward: 30,
    timePosted: "4h ago",
    sourceType: "rss",
    isAIGenerated: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1587560699334-cc4ff634909a?w=800&q=80",
  },
  {
    id: "3",
    question: "Should social media have age verification?",
    category: "Society",
    trending: false,
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80",
    source: "instagram",
    sourceLabel: "@socialmediatoday",
    totalVotes: 156789,
    yesPercentage: 78,
    xpReward: 20,
    timePosted: "6h ago",
    sourceType: "rss",
    isAIGenerated: false,
  },
  {
    id: "4",
    question: "Will electric cars fully replace gas cars by 2035?",
    category: "Environment",
    trending: true,
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80",
    source: "youtube",
    sourceLabel: "MKBHD",
    totalVotes: 45123,
    yesPercentage: 54,
    xpReward: 35,
    timePosted: "8h ago",
    sourceType: "youtube",
    isAIGenerated: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80",
  },
  {
    id: "5",
    question: "Should tipping culture be abolished?",
    category: "Culture",
    trending: false,
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    source: "tiktok",
    sourceLabel: "@serverlife",
    totalVotes: 234567,
    yesPercentage: 61,
    xpReward: 25,
    timePosted: "12h ago",
  },
  {
    id: "6",
    question: "Is the 4-day work week the future?",
    category: "Work",
    trending: true,
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=800&q=80",
    source: "news",
    sourceLabel: "BBC News",
    totalVotes: 178923,
    yesPercentage: 82,
    xpReward: 40,
    timePosted: "1d ago",
    sourceType: "rss",
    isAIGenerated: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=800&q=80",
  },
]

// ── Source colour map ─────────────────────────────────────────────────────────
export const SOURCE_COLORS: Record<
  MediaSource | IngestionSource,
  { bg: string; text: string; icon: string }
> = {
  // Legacy UI sources
  youtube:   { bg: "bg-red-500/10",       text: "text-red-500",      icon: "text-red-500"      },
  instagram: { bg: "bg-pink-500/10",      text: "text-pink-500",     icon: "text-pink-500"     },
  twitter:   { bg: "bg-sky-500/10",       text: "text-sky-500",      icon: "text-sky-500"      },
  news:      { bg: "bg-emerald-500/10",   text: "text-emerald-500",  icon: "text-emerald-500"  },
  tiktok:    { bg: "bg-foreground/10",    text: "text-foreground",   icon: "text-foreground"   },
  // Ingestion pipeline sources (US-10)
  rss:       { bg: "bg-orange-500/10",    text: "text-orange-500",   icon: "text-orange-500"   },
  gnews:     { bg: "bg-blue-500/10",      text: "text-blue-500",     icon: "text-blue-500"     },
  manual:    { bg: "bg-secondary",        text: "text-foreground",   icon: "text-muted-foreground" },
  business:  { bg: "bg-amber-500/15",     text: "text-amber-700 dark:text-amber-300", icon: "text-amber-600" },
}

// ── Source display labels ─────────────────────────────────────────────────────
export const SOURCE_LABELS: Record<IngestionSource, string> = {
  rss:     "News",
  youtube: "YouTube",
  gnews:   "Google News",
  manual:  "Pollify",
  business: "Sponsored",
}
